version: "3.8"
services:
  evf:
    privileged: true
    build:
      context: ${KEG_CONTEXT_PATH}
      dockerfile: ${KEG_DOCKER_FILE}
      args:
        - DOC_APP_PATH
        - DOC_CORE_PATH
        - DOC_COMPONENTS_PATH
        - DOC_JSUTILS_PATH
        - DOC_RESOLVER_PATH
        - DOC_RETHEME_PATH
        - EXPO_DEVTOOLS_LISTEN_ADDRESS
        - GIT_APP_URL
        - KEG_DOCKER_IP
        - KEG_IMAGE_FROM
        - KEG_EXEC_CMD
        - KEG_NODE_VERSION
        - KEG_NM_INSTALL
        - NODE_ENV
        - TAP
    environment:
      - CHOKIDAR_USEPOLLING
      - DOC_APP_PATH
      - DOC_CORE_PATH
      - DOC_COMPONENTS_PATH
      - DOC_JSUTILS_PATH
      - DOC_RESOLVER_PATH
      - DOC_RETHEME_PATH
      - EXPO_DEVTOOLS_LISTEN_ADDRESS
      - GIT_APP_URL
      - KEG_DOCKER_IP
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_NM_INSTALL
      - KEG_NODE_VERSION
      - NODE_ENV
      - TAP
