
env:
  # --- LOCAL ENV CONTEXT --- #
  COMPONENTS_PATH: "{{ cli.paths.components }}"
  RETHEME_PATH: "{{ cli.taps.retheme.path }}"
  RESOLVER_PATH: "{{ cli.paths.resolver }}"
  CLI_PATH: "{{ cli.paths.cli }}"
  
  # --- TAP ENV CONTEXT --- #

  # Docker / Docker Compose paths
  KEG_DOCKER_FILE: "{{ cli.taps.evf.path }}/container/Dockerfile"
  KEG_VALUES_FILE: "{{ cli.taps.evf.path }}/container/values.yml"
  KEG_MUTAGEN_FILE: "{{ cli.taps.evf.path }}/container/mutagen.yml"

  # The default docker-compose file path
  KEG_COMPOSE_DEFAULT: "{{ cli.paths.containers }}/tap/docker-compose.yml"
  # Can also define other an override compose files
  # Other compose files can loaded by setting an ENVS as follows:
    # KEG_COMPOSE_REPO="/path/to/override.yml"
    # KEG_COMPOSE_TAP_<ENV>: "/path/to/override.yml"
    # KEG_COMPOSE_<ENV>: "/path/to/override.yml"

  # The KEG_CONTEXT_PATH env should be the location of the tap being run
  # So it should NOT be set inside the .env file
  KEG_CONTEXT_PATH: "{{ cli.taps.evf.path }}"
  
  # Image to use when building evf
  KEG_BASE_IMAGE: ghcr.io/simpleviewinc/tap:master

  # Image to use when running evf
  KEG_IMAGE_FROM: ghcr.io/simpleviewinc/evf:master

  # --- DOCKER ENV CONTEXT --- #

  # Default location of the tap in the docker container
  DOC_APP_PATH: /keg/tap

  # Defines the location in a docker container for a dependency
  # This allows mutagen to know where to sync the local version of the dependency
  DOC_CORE_PATH: /keg/tap/node_modules/keg-core
  DOC_COMPONENTS_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/keg-components
  DOC_RETHEME_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/re-theme
  DOC_RESOLVER_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/tap-resolver
  DOC_JSUTILS_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/jsutils

  KEG_EXEC_CMD: tap:start

  # --- KEG-PROXY ENVs --- #

  # KEG_PROXY_HOST: custom-host.local.kegdev.xyz
    # To override the host header used by the proxy to route traffic to this container
    # add KEG_PROXY_HOST env and set it's value to the what the host header should be
    # the default is <container-context>-<git-branch-name>.<KEG_PROXY_HOST>
  
  # KEG_DOCKER_NETWORK: custom-docker-network
    # To override the default docker network used by the proxy to route traffic to this container
    # There should be no reason to need to overwrite this, but you can if you want
    # add KEG_PROXY_HOST env and set it's value to the what network should be used
    # the default is 'keg-hub-net'

  # KEG_PROXY_PORT - 80
    # If not set, then port 80 will be used by default
    # Port the proxy will route traffic to within the container
    # This should be the port the application expects to receive traffic on
    # This port should not be ( You can still do these things, but it's better not to )
    #   * Exposed publicly on the container
    #   * Bound to the host machine
  KEG_PROXY_PORT: 19006

  # --- GENERAL CONTEXT ENVs --- #

  # Image Build information
  IMAGE: evf
  VERSION: 1.0.0
  CONTAINER_NAME: evf
  CHOKIDAR_USEPOLLING: 1

  # Git tap url in github
  GIT_APP_URL: https://github.com/simpleviewinc/tap-events-force.git
  GIT_APP_BRANCH: master