name: image-deploy
on:
  push:
    branches:
      - tap-alias

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    name: Build tap image
    steps:
    - name: Cancel Previous Workflows In Progress
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}
    - name: Tap Build and Push
      id: tap-build-push
      uses: simpleviewinc/tap-build-action@0.0.4
      with:
        token: ${{ secrets.KEG_ADMIN_TOKEN }}
